site_name: Uni{form|corn} tool kit
markdown_extensions:
  - codehilite
  - attr_list
  - admonition
  - markdown.extensions.footnotes
  - markdown.extensions.smarty
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - pymdownx.emoji


extra:
  search:
    tokenizer: '[\s\-\.::]+'

theme:
  name: 'material'
  palette:
    primary: 'light-green'
    accent: 'deep orange'
  font:
    text: 'PT Serif'
    code: 'Inconsolata'
  logo: 'figs/logo_utk.png'

extra_css:
  - 'stylesheets/multilanguage_snippet.css'

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'javascript/multilanguage_snippet.js'

repo_name: 'utk-team/utk'
repo_url: 'https://github.com/utk-team/utk'
edit_uri: ''


docs_dir: 'doc'
site_dir: 'docs'

nav:
  - Home: 'index.md'
  - Samplers:
    - AAPatterns: 'samplers/AAPatterns.md'
    - ART: 'samplers/ART.md'
    - CMK: 'samplers/CMJ.md'
    - DartThrowing: 'samplers/DartThrowing.md'
    - FastPoisson: 'samplers/FastPoisson.md'
    - Fattal: 'samplers/Fattal.md'
    - Faure: 'samplers/Faure.md'
    - ForcedRandom: 'samplers/ForcedRandom.md'
    - Halton: 'samplers/Halton.md'
    - Hammersley: 'samplers/Hammersley.md'
    - HexagonalGrid: 'samplers/HexagonalGrid.md'
    - Korobov: 'samplers/Korobov.md'
    - Kronecker: 'samplers/Kronecker.md'
    - LDBN: 'samplers/LDBN.md'
    - LLoyd: 'samplers/LLoyd.md'
    - Niederreiter: 'samplers/Niederreiter.md'
    - NRooks: 'samplers/NRooks.md'
    - Penrose: 'samplers/Penrose.md'
    - PMJ: 'samplers/PMJ.md'
    - ProjectiveBlueNoise: 'samplers/ProjectiveBlueNoise.md'
    - Rank1: 'samplers/Rank1.md'
    - RegularGrid: 'samplers/RegularGrid.md'
    - SinglePeak: 'samplers/SinglePeak.md'
    - Sobol: 'samplers/Sobol.md'
    - Stratified: 'samplers/Stratified.md'
    - VenDerCorput: 'samplers/VanDerCorput.md'
    - Whitenoise: 'samplers/Whitenoise.md'
  - Metrics:
    - L2: 
    - GL2:
  